### ISSUE TITLE
!!!!!ВАЖНО!!!!

### ISSUE THREAD

**Issue by vmlakk** [gmankab/PrettyGit#1]
гманка расскажи анекдот

**Comment by gmankab** [comment]
> гманка расскажи анекдот

Купил мужик на рынке за 500 баксов обезьяну и захотел ее научить разговаривать. Разговаривать не научил, а научил только одному слову «конечно». «Ну, – подумал, – зачем мне такая обезьяна!» Понес продавать на рынок обратно. Подходит к нему мужик, спрашивает:
– Сколько стоит обезьяна?
– 1000 баксов.
– А че так дорого?
– А она разговаривать умеет.
– Не ври!
– Подойди сам спроси.
Ну тот подходит, спрашивает:
– Ты разговаривать умеешь?
Та:
– Конечно.
Мужик купил, принес домой, посадил на стол, спрашивает:
– Убираться дома будешь?
Та:
– Конечно.
– Детям с уроками помогать будешь?
– Конечно.
– Пить будешь?
– Конечно.
– Курить будешь?
– Конечно.
«Ну, – подумал, – не нужна мне такая обезьяна!» Понес продавать на рынок. Подходит к нему бедный золотоискатель:
– Сколько стоит обезьяна?
– 2000 баксов.
– А че так дорого?
– А она знает, где клад лежит.
– Не ври!
– Подойди сам спроси.
Тот подходит, спрашивает:
– Ты знаешь, где клад зарыт?
Та:
– Конечно.
Купил, принес домой, посадил на стол, раскрыл карту (пальцем в карту):
– Тут??
Та:
– Конечно.
Забрал обезьяну, поехал на Север, заехал чуть ли не на Северный полюс.
Спрашивает:
– Тут копать?
– Конечно.
Разрыл сугроб.
– А может, глубже?
– Конечно.
Глубже копает.
– А может, шире?
– Конечно.
Шире копает. Весь день копал, устал, спрашивает:
– Обезьяна, скажи честно, ты меня обманываешь?
– Конечно.
Разозлился, замахивается лопатой:
– Может тебя ударить?
– Не надо.

**Comment by Arwichok** [comment]
Чому не державною?

**Comment by gmankab** [comment]
> Чому не державною?

Купив чоловік на ринку за 500 доларів мавпу і захотів її навчити розмовляти.  Розмовляти не навчив, а навчив лише одного слова «звичайно».  "Ну, - подумав, - навіщо мені така мавпа!"  Поніс продавати ринку назад.  Підходить до нього мужик, питає:
 – Скільки коштує мавпа?
 - 1000 доларів.
 - А що так дорого?
 – А вона розмовляти вміє.
 - Не бреши!
 - Підійди сам спитай.
 Ну той підходить, питає:
 - Ти розмовляти вмієш?
 Та:
 - Звичайно.
 Чоловік купив, приніс додому, посадив на стіл, питає:
 - Забиратися вдома будеш?
 Та:
 - Звичайно.
 – Дітям з уроками допомагатимеш?
 - Звичайно.
 - Пити будеш?
 - Звичайно.
 – Куритимеш?
 - Звичайно.
 "Ну, - подумав, - не потрібна мені така мавпа!"  Поніс продавати на ринок.  Підходить до нього бідний золотошукач.
 – Скільки коштує мавпа?
 - 2000 доларів.
 - А що так дорого?
 – А вона знає, де скарб лежить.
 - Не бреши!
 - Підійди сам спитай.
 Той підходить, питає:
 - Ти знаєш, де скарб закопаний?
 Та:
 - Звичайно.
 Купив, приніс додому, посадив на стіл, розкрив карту (пальцем у карту):
 - Тут?
 Та:
 - Звичайно.
 Забрав мавпу, поїхав на Північ, заїхав мало не на Північний полюс.
 Запитує:
 - Тут копати?
 - Звичайно.
 Розрив кучугуру.
 - А може, глибше?
 - Звичайно.
 Глибоко копає.
 - А може, ширше?
 - Звичайно.
 Ширше копає.  Весь день копав, втомився, питає:
 - Мавпо, скажи чесно, ти мене обманюєш?
 - Звичайно.
 Розлютився, замахується лопатою:
 - Може тебе вдарити?
 - Не треба.
